remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: BDIS Data & Analytics Prototyping
description: This site includes prototypes developed by the BDIS Data & Analytics Team. All items on this page are in development and not final. 
